#!/bin/bash -ex
#
# This script is run on travis for the install stage of mac builds.
#

CACHEDIR=${HOME}/Cache
mkdir -p ${CACHEDIR}

sw_vers
xcodebuild -version

version=5.12.7
versionmm=$(echo ${version} | cut -d. -f1,2)

if [ ! -f ${CACHEDIR}/stage ]; then
  echo "stage0" > ${CACHEDIR}/stage
fi

stage=$(cat ${CACHEDIR}/stage)

case $stage in

  stage0)
  mkdir -p ${CACHEDIR}/build/qt5-build
  cd ${CACHEDIR}/build
  wget -nv https://download.qt.io/archive/qt/${versionmm}/${version}/single/qt-everywhere-src-${version}.tar.xz
  tar -xJf qt-everywhere-src-${version}.tar.xz
  /bin/rm qt-everywhere-src-${version}.tar.xz
  excludes=( qtdatavis3d qtwebglplugin qtvirtualkeyboard qtcharts qtnetworkauth)
  for component in ${excludes[@]}
  do
    /bin/rm -fr qt-everywhere-src-${version}/$component
  done

  cd ${CACHEDIR}/build/qt5-build
  ../qt-everywhere-src-${version}/configure --prefix=${CACHEDIR}/Qt/${version}/clang_64 -opensource -confirm-license -nomake examples -nomake tests -release
  echo "stage1" > ${CACHEDIR}/stage
  ;;

  stage1)
  cd ${CACHEDIR}/build/qt5-build
  status=0
  # must timeout and intercept status before travis times out at 50 minutes from job start.
  # must not exceed travis log limit.
  # must not be quiet for too long.
  while sleep 60; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
  gtimeout -s SIGTERM 40m make -j4  1>>build.log || status=$?
  kill %1
  if [ $status -eq 0 ]; then
    echo "stage2" > ${CACHEDIR}/stage
  elif [ $status -eq 124 ]; then
    # timeout
    echo "build timed out, repeat"
  else
    echo "make status unexpected, $status"
  fi
  ;;

  stage2)
  cd ${CACHEDIR}/build/qt5-build
  make install
  echo "stage 3" > ${CACHEDIR}/stage
  ;;

  stage3)
  echo "Build complete"
  /bin/rm -fr ${CACHEDIR}/build
  ${CACHEDIR}/Qt/${version}/clang_64/bin/qmake -query
  ;;

esac
