#!/bin/bash -ex
#
# This script is run on travis for the install stage of mac builds.
#

# our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
CACHEDIR=${HOME}/Cache

#if [ -f "${CACHEDIR}/timestamp" ]; then
#  echo "Using cached Qt."
#  echo "If you need to clear the cache see"
#  echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
#  cat "${CACHEDIR}/timestamp"
#else
  sw_vers
  xcodebuild -version
  if [ ! -z "${SECRETVAR+x}" ] ; then
    echo -n "SECRETVAR hash: "
    echo -n "$SECRETVAR" | openssl dgst -sha512 | cut -d " " -f 2
  else
    echo no secrets available.
  fi
  if [ -f ${CACHEDIR}/timestamp ]; then
    echo "old cache found"
    cat ${CACHEDIR}/timestamp
  fi
  rm -fr ${CACHEDIR}
  mkdir -p ${CACHEDIR}
  cd ${CACHEDIR}
  date > timestamp
#fi
